### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by uonick** [sky790312/vue2-project-boilerplate#1]
Run `npm install && npm run dev`

![screen shot 2017-06-17 at 03 38 46](https://user-images.githubusercontent.com/365029/27248594-7edef152-530e-11e7-9ae0-2cd066137ded.png)

In the browser:

![screen shot 2017-06-17 at 03 39 20](https://user-images.githubusercontent.com/365029/27248601-94753b70-530e-11e7-8579-4313edd7eee5.png)

Page2:

![screen shot 2017-06-17 at 03 41 29](https://user-images.githubusercontent.com/365029/27248621-e39f02b2-530e-11e7-8eb8-5fac5f7e76d6.png)

Close `h1` tag =)

**Comment by uonick** [comment]
... and Page1:

![screen shot 2017-06-17 at 03 42 51](https://user-images.githubusercontent.com/365029/27248628-147d8962-530f-11e7-9ef6-d186ab16f77c.png)

**Comment by uonick** [comment]
after correcting the tags you will get: 

![screen shot 2017-06-17 at 03 44 48](https://user-images.githubusercontent.com/365029/27248644-58466f88-530f-11e7-8862-48d3db31aed9.png)

**Comment by sky790312** [comment]
I think it's version issue like following:
https://github.com/kazupon/vue-i18n/issues/117
The project is set up more than six months ago, it works fine on my computer.
I'm not sure if the setting works fine now... I can find a new environment to test one day.
By the way. thanks for reminding the h1 tag error.
